[package]
name = "glitchtool"
version = "0.1.0"
authors = [ "ash lea <example@thisismyactual.email>" ]
edition = "2018"

[dependencies]
azul = { git = "https://github.com/ashkitten/azul", branch = "glitchtool" }
image = "0.22"
fuse_mt = "0.5"
libc = "0.2"
fuse = "0.3"
time = "0.1"
