[package]
name = "glitchtool"
version = "0.1.0"
authors = [ "ash lea <example@thisismyactual.email>" ]
edition = "2018"

[dependencies]
azul = { git = "https://github.com/ashkitten/azul", branch = "glitchtool", features = [ "image_loading" ] }
